import type { ASCIIAppearance } from "@/lib/ascii/ascii-config";
import {
  APPEARANCE as CarAppearance,
  CHARS as CarChars,
  FPS as CarFps,
  FRAMES as CarFrames,
} from "./car";

import {
  APPEARANCE as FireAppearance,
  CHARS as FireChars,
  FPS as FireFps,
  FRAMES as FireFrames,
} from "./fire";

import {
  APPEARANCE as FlowerAppearance,
  CHARS as FlowerChars,
  FPS as FlowerFps,
  FRAMES as FlowerFrames,
} from "./flower";

import {
  APPEARANCE as MemeAppearance,
  CHARS as MemeChars,
  FPS as MemeFps,
  FRAMES as MemeFrames,
} from "./meme";

import {
  APPEARANCE as MoonKnightMrKnightAppearance,
  CHARS as MoonKnightMrKnightChars,
  FPS as MoonKnightMrKnightFps,
  FRAMES as MoonKnightMrKnightFrames,
} from "./moon-knight-mr-knight";

import {
  APPEARANCE as StrokeAppearance,
  CHARS as StrokeChars,
  FPS as StrokeFps,
  FRAMES as StrokeFrames,
} from "./stroke";

export interface ASCIIShowcaseEntry {
  id: string;
  title: string;
  description: string;
  filename: string;
  accentColor: string;
  componentName: string;
  frames: string[];
  fps: number;
  chars: string;
  appearance: ASCIIAppearance;
}

// This file is auto-generated by scripts/generate-ascii-index.mjs.
export const ASCII_SHOWCASE: ASCIIShowcaseEntry[] = [
  {
    id: "car",
    title: "Car",
    description: "ASCII car animation.",
    filename: "car.tsx",
    accentColor: "#B54B00",
    componentName: "Car",
    frames: CarFrames,
    fps: CarFps,
    chars: CarChars,
    appearance: CarAppearance as ASCIIAppearance,
  },
  {
    id: "fire",
    title: "Fire",
    description: "ASCII fire animation.",
    filename: "fire.tsx",
    accentColor: "#B54B00",
    componentName: "Ascii",
    frames: FireFrames,
    fps: FireFps,
    chars: FireChars,
    appearance: FireAppearance as ASCIIAppearance,
  },
  {
    id: "flower",
    title: "Flower",
    description: "ASCII flower animation.",
    filename: "flower.tsx",
    accentColor: "#B54B00",
    componentName: "Ascii",
    frames: FlowerFrames,
    fps: FlowerFps,
    chars: FlowerChars,
    appearance: FlowerAppearance as ASCIIAppearance,
  },
  {
    id: "meme",
    title: "Meme",
    description: "ASCII meme animation.",
    filename: "meme.tsx",
    accentColor: "#B54B00",
    componentName: "Meme",
    frames: MemeFrames,
    fps: MemeFps,
    chars: MemeChars,
    appearance: MemeAppearance as ASCIIAppearance,
  },
  {
    id: "moon-knight-mr-knight",
    title: "Moon Knight Mr Knight",
    description: "ASCII moon-knight-mr-knight animation.",
    filename: "moon-knight-mr-knight.tsx",
    accentColor: "#B54B00",
    componentName: "MoonKnightMrKnight",
    frames: MoonKnightMrKnightFrames,
    fps: MoonKnightMrKnightFps,
    chars: MoonKnightMrKnightChars,
    appearance: MoonKnightMrKnightAppearance as ASCIIAppearance,
  },
  {
    id: "stroke",
    title: "Stroke",
    description: "ASCII stroke animation.",
    filename: "stroke.tsx",
    accentColor: "#B54B00",
    componentName: "StrokeAscii",
    frames: StrokeFrames,
    fps: StrokeFps,
    chars: StrokeChars,
    appearance: StrokeAppearance as ASCIIAppearance,
  },
];

export {
  APPEARANCE as CAR_APPEARANCE,
  CHARS as CAR_CHARS,
  FPS as CAR_FPS,
  FRAMES as CAR_FRAMES,
} from "./car";

export {
  APPEARANCE as FIRE_APPEARANCE,
  CHARS as FIRE_CHARS,
  FPS as FIRE_FPS,
  FRAMES as FIRE_FRAMES,
} from "./fire";

export {
  APPEARANCE as FLOWER_APPEARANCE,
  CHARS as FLOWER_CHARS,
  FPS as FLOWER_FPS,
  FRAMES as FLOWER_FRAMES,
} from "./flower";

export {
  APPEARANCE as MEME_APPEARANCE,
  CHARS as MEME_CHARS,
  FPS as MEME_FPS,
  FRAMES as MEME_FRAMES,
} from "./meme";

export {
  APPEARANCE as MOON_KNIGHT_MR_KNIGHT_APPEARANCE,
  CHARS as MOON_KNIGHT_MR_KNIGHT_CHARS,
  FPS as MOON_KNIGHT_MR_KNIGHT_FPS,
  FRAMES as MOON_KNIGHT_MR_KNIGHT_FRAMES,
} from "./moon-knight-mr-knight";

export {
  APPEARANCE as STROKE_APPEARANCE,
  CHARS as STROKE_CHARS,
  FPS as STROKE_FPS,
  FRAMES as STROKE_FRAMES,
} from "./stroke";
